logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: ${ENV_LOG_REQUESTS:DEBUG}
          servlet:
            DispatcherServlet: INFO
    root: ${ENV_LOG_LEVEL:INFO}
  pattern:
    console: '%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) [%thread] %cyan(%class{36}.%M %L) - %msg%n'
    file: '%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %d{yyyy-MM-dd HH:mm:ss} %-5level %class{36}.%M %L - %msg%n'

server:
  port: ${ENV_PORT:9080}
  servlet:
    contextPath: ${ENV_CTX_PATH:/spring-boot-ms-model}

spring:
  http:
    converters:
      preferred-json-mapper: gson
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/springbootmsmodel?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  profiles:
    active: ${ENV:local}